package sdl

// #cgo pkg-config: sdl2
// #include <SDL2/SDL.h>
import "C"

const (
	// init flags

	INIT_AUDIO       = C.SDL_INIT_AUDIO
	INIT_VIDEO       = C.SDL_INIT_VIDEO
	INIT_TIMER       = C.SDL_INIT_TIMER
	INIT_JOYSTICK    = C.SDL_INIT_JOYSTICK
	INIT_NOPARACHUTE = C.SDL_INIT_NOPARACHUTE
	INIT_EVERYTHING  = C.SDL_INIT_EVERYTHING

	// setvideo flags

	SWSURFACE = C.SDL_SWSURFACE
	RLEACCEL  = C.SDL_RLEACCEL
	PREALLOC  = C.SDL_PREALLOC

	// Window flags

	WINDOW_FULLSCREEN         = C.SDL_WINDOW_FULLSCREEN
	WINDOW_FULLSCREEN_DESKTOP = C.SDL_WINDOW_FULLSCREEN_DESKTOP
	WINDOW_OPENGL             = C.SDL_WINDOW_OPENGL
	WINDOW_HIDDEN             = C.SDL_WINDOW_HIDDEN
	WINDOW_BORDERLESS         = C.SDL_WINDOW_BORDERLESS
	WINDOW_RESIZABLE          = C.SDL_WINDOW_RESIZABLE
	WINDOW_MINIMIZED          = C.SDL_WINDOW_MINIMIZED
	WINDOW_MAXIMIZED          = C.SDL_WINDOW_MAXIMIZED
	WINDOW_INPUT_GRABBED      = C.SDL_WINDOW_INPUT_GRABBED
	WINDOW_SHOWN              = C.SDL_WINDOW_SHOWN
	WINDOW_INPUT_FOCUS        = C.SDL_WINDOW_INPUT_FOCUS
	WINDOW_MOUSE_FOCUS        = C.SDL_WINDOW_MOUSE_FOCUS
	WINDOW_FOREIGN            = C.SDL_WINDOW_FOREIGN

	WINDOWPOS_UNDEFINED = C.SDL_WINDOWPOS_UNDEFINED

	// Render flags

	RENDERER_SOFTWARE      = C.SDL_RENDERER_SOFTWARE
	RENDERER_ACCELERATED   = C.SDL_RENDERER_ACCELERATED
	RENDERER_PRESENTVSYNC  = C.SDL_RENDERER_PRESENTVSYNC
	RENDERER_TARGETTEXTURE = C.SDL_RENDERER_TARGETTEXTURE

	// More setvideo flags: GLattr enumeration

	GL_RED_SIZE           = C.SDL_GL_RED_SIZE
	GL_GREEN_SIZE         = C.SDL_GL_GREEN_SIZE
	GL_BLUE_SIZE          = C.SDL_GL_BLUE_SIZE
	GL_ALPHA_SIZE         = C.SDL_GL_ALPHA_SIZE
	GL_BUFFER_SIZE        = C.SDL_GL_BUFFER_SIZE
	GL_DOUBLEBUFFER       = C.SDL_GL_DOUBLEBUFFER
	GL_DEPTH_SIZE         = C.SDL_GL_DEPTH_SIZE
	GL_STENCIL_SIZE       = C.SDL_GL_STENCIL_SIZE
	GL_ACCUM_RED_SIZE     = C.SDL_GL_ACCUM_RED_SIZE
	GL_ACCUM_GREEN_SIZE   = C.SDL_GL_ACCUM_GREEN_SIZE
	GL_ACCUM_BLUE_SIZE    = C.SDL_GL_ACCUM_BLUE_SIZE
	GL_ACCUM_ALPHA_SIZE   = C.SDL_GL_ACCUM_ALPHA_SIZE
	GL_STEREO             = C.SDL_GL_STEREO
	GL_MULTISAMPLEBUFFERS = C.SDL_GL_MULTISAMPLEBUFFERS
	GL_MULTISAMPLESAMPLES = C.SDL_GL_MULTISAMPLESAMPLES
	GL_ACCELERATED_VISUAL = C.SDL_GL_ACCELERATED_VISUAL
	// GL_SWAP_CONTROL       = C.SDL_GL_SWAP_CONTROL

	// event types

	KEYDOWN         = C.SDL_KEYDOWN
	KEYUP           = C.SDL_KEYUP
	MOUSEMOTION     = C.SDL_MOUSEMOTION
	MOUSEBUTTONDOWN = C.SDL_MOUSEBUTTONDOWN
	MOUSEBUTTONUP   = C.SDL_MOUSEBUTTONUP
	JOYAXISMOTION   = C.SDL_JOYAXISMOTION
	JOYBALLMOTION   = C.SDL_JOYBALLMOTION
	JOYHATMOTION    = C.SDL_JOYHATMOTION
	JOYBUTTONDOWN   = C.SDL_JOYBUTTONDOWN
	JOYBUTTONUP     = C.SDL_JOYBUTTONUP
	QUIT            = C.SDL_QUIT
	SYSWMEVENT      = C.SDL_SYSWMEVENT
	USEREVENT       = C.SDL_USEREVENT

	// window events
	WINDOWEVENT_SHOWN        = C.SDL_WINDOWEVENT_SHOWN
	WINDOWEVENT_HIDDEN       = C.SDL_WINDOWEVENT_HIDDEN
	WINDOWEVENT_EXPOSED      = C.SDL_WINDOWEVENT_EXPOSED
	WINDOWEVENT_MOVED        = C.SDL_WINDOWEVENT_MOVED
	WINDOWEVENT_RESIZED      = C.SDL_WINDOWEVENT_RESIZED
	WINDOWEVENT_SIZE_CHANGED = C.SDL_WINDOWEVENT_SIZE_CHANGED
	WINDOWEVENT_MINIMIZED    = C.SDL_WINDOWEVENT_MINIMIZED
	WINDOWEVENT_MAXIMIZED    = C.SDL_WINDOWEVENT_MAXIMIZED
	WINDOWEVENT_RESTORED     = C.SDL_WINDOWEVENT_RESTORED
	WINDOWEVENT_ENTER        = C.SDL_WINDOWEVENT_ENTER
	WINDOWEVENT_LEAVE        = C.SDL_WINDOWEVENT_LEAVE
	WINDOWEVENT_FOCUS_GAINED = C.SDL_WINDOWEVENT_FOCUS_GAINED
	WINDOWEVENT_FOCUS_LOST   = C.SDL_WINDOWEVENT_FOCUS_LOST
	WINDOWEVENT_CLOSE        = C.SDL_WINDOWEVENT_CLOSE

	// event state

	QUERY   = C.SDL_QUERY
	DISABLE = C.SDL_DISABLE
	ENABLE  = C.SDL_ENABLE

	// keys
	K_UNKNOWN      = C.SDLK_UNKNOWN
	K_BACKSPACE    = C.SDLK_BACKSPACE
	K_TAB          = C.SDLK_TAB
	K_CLEAR        = C.SDLK_CLEAR
	K_RETURN       = C.SDLK_RETURN
	K_PAUSE        = C.SDLK_PAUSE
	K_ESCAPE       = C.SDLK_ESCAPE
	K_SPACE        = C.SDLK_SPACE
	K_EXCLAIM      = C.SDLK_EXCLAIM
	K_QUOTEDBL     = C.SDLK_QUOTEDBL
	K_HASH         = C.SDLK_HASH
	K_DOLLAR       = C.SDLK_DOLLAR
	K_AMPERSAND    = C.SDLK_AMPERSAND
	K_QUOTE        = C.SDLK_QUOTE
	K_LEFTPAREN    = C.SDLK_LEFTPAREN
	K_RIGHTPAREN   = C.SDLK_RIGHTPAREN
	K_ASTERISK     = C.SDLK_ASTERISK
	K_PLUS         = C.SDLK_PLUS
	K_COMMA        = C.SDLK_COMMA
	K_MINUS        = C.SDLK_MINUS
	K_PERIOD       = C.SDLK_PERIOD
	K_SLASH        = C.SDLK_SLASH
	K_0            = C.SDLK_0
	K_1            = C.SDLK_1
	K_2            = C.SDLK_2
	K_3            = C.SDLK_3
	K_4            = C.SDLK_4
	K_5            = C.SDLK_5
	K_6            = C.SDLK_6
	K_7            = C.SDLK_7
	K_8            = C.SDLK_8
	K_9            = C.SDLK_9
	K_COLON        = C.SDLK_COLON
	K_SEMICOLON    = C.SDLK_SEMICOLON
	K_LESS         = C.SDLK_LESS
	K_EQUALS       = C.SDLK_EQUALS
	K_GREATER      = C.SDLK_GREATER
	K_QUESTION     = C.SDLK_QUESTION
	K_AT           = C.SDLK_AT
	K_LEFTBRACKET  = C.SDLK_LEFTBRACKET
	K_BACKSLASH    = C.SDLK_BACKSLASH
	K_RIGHTBRACKET = C.SDLK_RIGHTBRACKET
	K_CARET        = C.SDLK_CARET
	K_UNDERSCORE   = C.SDLK_UNDERSCORE
	K_BACKQUOTE    = C.SDLK_BACKQUOTE
	K_a            = C.SDLK_a
	K_b            = C.SDLK_b
	K_c            = C.SDLK_c
	K_d            = C.SDLK_d
	K_e            = C.SDLK_e
	K_f            = C.SDLK_f
	K_g            = C.SDLK_g
	K_h            = C.SDLK_h
	K_i            = C.SDLK_i
	K_j            = C.SDLK_j
	K_k            = C.SDLK_k
	K_l            = C.SDLK_l
	K_m            = C.SDLK_m
	K_n            = C.SDLK_n
	K_o            = C.SDLK_o
	K_p            = C.SDLK_p
	K_q            = C.SDLK_q
	K_r            = C.SDLK_r
	K_s            = C.SDLK_s
	K_t            = C.SDLK_t
	K_u            = C.SDLK_u
	K_v            = C.SDLK_v
	K_w            = C.SDLK_w
	K_x            = C.SDLK_x
	K_y            = C.SDLK_y
	K_z            = C.SDLK_z
	K_DELETE       = C.SDLK_DELETE
	K_KP_PERIOD    = C.SDLK_KP_PERIOD
	K_KP_DIVIDE    = C.SDLK_KP_DIVIDE
	K_KP_MULTIPLY  = C.SDLK_KP_MULTIPLY
	K_KP_MINUS     = C.SDLK_KP_MINUS
	K_KP_PLUS      = C.SDLK_KP_PLUS
	K_KP_ENTER     = C.SDLK_KP_ENTER
	K_KP_EQUALS    = C.SDLK_KP_EQUALS
	K_UP           = C.SDLK_UP
	K_DOWN         = C.SDLK_DOWN
	K_RIGHT        = C.SDLK_RIGHT
	K_LEFT         = C.SDLK_LEFT
	K_INSERT       = C.SDLK_INSERT
	K_HOME         = C.SDLK_HOME
	K_END          = C.SDLK_END
	K_PAGEUP       = C.SDLK_PAGEUP
	K_PAGEDOWN     = C.SDLK_PAGEDOWN
	K_F1           = C.SDLK_F1
	K_F2           = C.SDLK_F2
	K_F3           = C.SDLK_F3
	K_F4           = C.SDLK_F4
	K_F5           = C.SDLK_F5
	K_F6           = C.SDLK_F6
	K_F7           = C.SDLK_F7
	K_F8           = C.SDLK_F8
	K_F9           = C.SDLK_F9
	K_F10          = C.SDLK_F10
	K_F11          = C.SDLK_F11
	K_F12          = C.SDLK_F12
	K_F13          = C.SDLK_F13
	K_F14          = C.SDLK_F14
	K_F15          = C.SDLK_F15
	K_CAPSLOCK     = C.SDLK_CAPSLOCK
	K_RSHIFT       = C.SDLK_RSHIFT
	K_LSHIFT       = C.SDLK_LSHIFT
	K_RCTRL        = C.SDLK_RCTRL
	K_LCTRL        = C.SDLK_LCTRL
	K_RALT         = C.SDLK_RALT
	K_LALT         = C.SDLK_LALT
	K_MODE         = C.SDLK_MODE
	K_HELP         = C.SDLK_HELP
	K_SYSREQ       = C.SDLK_SYSREQ
	K_MENU         = C.SDLK_MENU
	K_POWER        = C.SDLK_POWER
	K_UNDO         = C.SDLK_UNDO

	// key mods

	KMOD_NONE     = C.KMOD_NONE
	KMOD_LSHIFT   = C.KMOD_LSHIFT
	KMOD_RSHIFT   = C.KMOD_RSHIFT
	KMOD_LCTRL    = C.KMOD_LCTRL
	KMOD_RCTRL    = C.KMOD_RCTRL
	KMOD_LALT     = C.KMOD_LALT
	KMOD_RALT     = C.KMOD_RALT
	KMOD_NUM      = C.KMOD_NUM
	KMOD_CAPS     = C.KMOD_CAPS
	KMOD_MODE     = C.KMOD_MODE
	KMOD_RESERVED = C.KMOD_RESERVED
	KMOD_LGUI     = C.KMOD_LGUI
	KMOD_RGUI     = C.KMOD_RGUI
	KMOD_CTRL     = C.KMOD_CTRL
	KMOD_SHIFT    = C.KMOD_SHIFT
	KMOD_ALT      = C.KMOD_ALT
	KMOD_GUI      = C.KMOD_GUI

	// hat states

	HAT_CENTERED  = C.SDL_HAT_CENTERED
	HAT_UP        = C.SDL_HAT_UP
	HAT_RIGHT     = C.SDL_HAT_RIGHT
	HAT_DOWN      = C.SDL_HAT_DOWN
	HAT_LEFT      = C.SDL_HAT_LEFT
	HAT_RIGHTUP   = C.SDL_HAT_RIGHTUP
	HAT_RIGHTDOWN = C.SDL_HAT_RIGHTDOWN
	HAT_LEFTUP    = C.SDL_HAT_LEFTUP
	HAT_LEFTDOWN  = C.SDL_HAT_LEFTDOWN

	// keyboard/mouse state

	RELEASED = C.SDL_RELEASED
	PRESSED  = C.SDL_PRESSED

	// mouse button constants

	BUTTON_LEFT   = C.SDL_BUTTON_LEFT
	BUTTON_MIDDLE = C.SDL_BUTTON_MIDDLE
	BUTTON_RIGHT  = C.SDL_BUTTON_RIGHT
	BUTTON_X1     = C.SDL_BUTTON_X1
	BUTTON_X2     = C.SDL_BUTTON_X2

	// mouse button masks

	BUTTON_LMASK  = 1 << (BUTTON_LEFT - 1)
	BUTTON_MMASK  = 1 << (BUTTON_MIDDLE - 1)
	BUTTON_RMASK  = 1 << (BUTTON_RIGHT - 1)
	BUTTON_X1MASK = 1 << (BUTTON_X1 - 1)
	BUTTON_X2MASK = 1 << (BUTTON_X2 - 1)

	// message boxes

	MESSAGEBOX_ERROR       = C.SDL_MESSAGEBOX_ERROR
	MESSAGEBOX_WARNING     = C.SDL_MESSAGEBOX_WARNING
	MESSAGEBOX_INFORMATION = C.SDL_MESSAGEBOX_INFORMATION

	// pixel format

	PIXELFORMAT_UNKNOWN     = C.SDL_PIXELFORMAT_UNKNOWN
	PIXELFORMAT_INDEX1LSB   = C.SDL_PIXELFORMAT_INDEX1LSB
	PIXELFORMAT_INDEX1MSB   = C.SDL_PIXELFORMAT_INDEX1MSB
	PIXELFORMAT_INDEX4LSB   = C.SDL_PIXELFORMAT_INDEX4LSB
	PIXELFORMAT_INDEX4MSB   = C.SDL_PIXELFORMAT_INDEX4MSB
	PIXELFORMAT_INDEX8      = C.SDL_PIXELFORMAT_INDEX8
	PIXELFORMAT_RGB332      = C.SDL_PIXELFORMAT_RGB332
	PIXELFORMAT_RGB444      = C.SDL_PIXELFORMAT_RGB444
	PIXELFORMAT_RGB555      = C.SDL_PIXELFORMAT_RGB555
	PIXELFORMAT_BGR555      = C.SDL_PIXELFORMAT_BGR555
	PIXELFORMAT_ARGB4444    = C.SDL_PIXELFORMAT_ARGB4444
	PIXELFORMAT_RGBA4444    = C.SDL_PIXELFORMAT_RGBA4444
	PIXELFORMAT_ABGR4444    = C.SDL_PIXELFORMAT_ABGR4444
	PIXELFORMAT_BGRA4444    = C.SDL_PIXELFORMAT_BGRA4444
	PIXELFORMAT_ARGB1555    = C.SDL_PIXELFORMAT_ARGB1555
	PIXELFORMAT_RGBA5551    = C.SDL_PIXELFORMAT_RGBA5551
	PIXELFORMAT_ABGR1555    = C.SDL_PIXELFORMAT_ABGR1555
	PIXELFORMAT_BGRA5551    = C.SDL_PIXELFORMAT_BGRA5551
	PIXELFORMAT_RGB565      = C.SDL_PIXELFORMAT_RGB565
	PIXELFORMAT_BGR565      = C.SDL_PIXELFORMAT_BGR565
	PIXELFORMAT_RGB24       = C.SDL_PIXELFORMAT_RGB24
	PIXELFORMAT_BGR24       = C.SDL_PIXELFORMAT_BGR24
	PIXELFORMAT_RGB888      = C.SDL_PIXELFORMAT_RGB888
	PIXELFORMAT_RGBX8888    = C.SDL_PIXELFORMAT_RGBX8888
	PIXELFORMAT_BGR888      = C.SDL_PIXELFORMAT_BGR888
	PIXELFORMAT_BGRX8888    = C.SDL_PIXELFORMAT_BGRX8888
	PIXELFORMAT_ARGB8888    = C.SDL_PIXELFORMAT_ARGB8888
	PIXELFORMAT_RGBA8888    = C.SDL_PIXELFORMAT_RGBA8888
	PIXELFORMAT_ABGR8888    = C.SDL_PIXELFORMAT_ABGR8888
	PIXELFORMAT_BGRA8888    = C.SDL_PIXELFORMAT_BGRA8888
	PIXELFORMAT_ARGB2101010 = C.SDL_PIXELFORMAT_ARGB2101010
	PIXELFORMAT_YV12        = C.SDL_PIXELFORMAT_YV12
	PIXELFORMAT_IYUV        = C.SDL_PIXELFORMAT_IYUV
	PIXELFORMAT_YUY2        = C.SDL_PIXELFORMAT_YUY2
	PIXELFORMAT_UYVY        = C.SDL_PIXELFORMAT_UYVY
	PIXELFORMAT_YVYU        = C.SDL_PIXELFORMAT_YVYU

	// texture access

	TEXTUREACCESS_STATIC    = C.SDL_TEXTUREACCESS_STATIC
	TEXTUREACCESS_STREAMING = C.SDL_TEXTUREACCESS_STREAMING
)
